package com.test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class TestFlatMapFunction {
	
	public static void main(String arg[]) {
		List<List<Integer>> number = new ArrayList<>();
		number.add(Arrays.asList(1,2));
		number.add(Arrays.asList(3,4));
		number.add(Arrays.asList(5,6));
		System.out.println("List of List "+number);
		List<Integer> flatList = number.stream().flatMap(l->l.stream()).collect(Collectors.toList());
		System.out.println("List generated by flat map "+flatList);
	}

}
